### ISSUE TITLE
CreateCard

### ISSUE THREAD

**Issue by lasuridze** [MilesBDyson/RFID-RC522#1]
Press Enter to exit
Card Type [Master,Super,User]: q
First Name [Max 48 Char]: w
Last Name [Max 48 Char]:e
Employee ID [Max 16 Char]:q
Department Number [Max 16 Char]:q
Title [Max 16 Char]: q
Waiting for Tag...

Traceback (most recent call last):
  File "CreateCard.py", line 128, in <module>
    util.rewrite(sector[2][0],cardtype)
  File "/home/toka/RFID-RC522/examples/rc522/util.py", line 119, in rewrite
    error = self.rfid.write(block_address, data)
  File "/home/toka/RFID-RC522/examples/rc522/rfid.py", line 376, in write
    crc = self.calculate_crc(buf_w)
  File "/home/toka/RFID-RC522/examples/rc522/rfid.py", line 251, in calculate_crc
    self.dev_write(0x09, data[i])
  File "/home/toka/RFID-RC522/examples/rc522/rfid.py", line 107, in dev_write
    self.spi_transfer([(address << 1) & 0x7E, value])
  File "/home/toka/RFID-RC522/examples/rc522/rfid.py", line 101, in spi_transfer
    r = self.spi.xfer2(data)
TypeError: Non-Int/Long value in arguments: 766e91e0.

**Comment by lethang47** [comment]
Hello, I can't run ReadCard.py file, It stops at wait_for_tag function. Can you help me?

**Comment by MilesBDyson** [comment]
it was working at the time i posted it no time to work on it now.. maybe something changed in python
